// export const API_URL  = 'http://localhost:3000'
// export const IMG_URL = "http://localhost:3000/images/"
// export const API_URL  = 'https://server-5fk2k38vs-codebrocamp-gmailcoms-projects.vercel.app'
// export const IMG_URL = "https://server-5fk2k38vs-codebrocamp-gmailcoms-projects.vercel.app/images/"
// export const API_URL  = '"https://server-60j6msyzb-codebrocamp-gmailcoms-projects.vercel.app"'
// export const IMG_URL = "https://server-60j6msyzb-codebrocamp-gmailcoms-projects.vercel.app/images/"
// export const API_URL  = "https://server-60j6msyzb-codebrocamp-gmailcoms-projects.vercel.app"
// export const IMG_URL = "https://server-60j6msyzb-codebrocamp-gmailcoms-projects.vercel.app/images/"
export const API_URL  = "https://server-3seejeyjs-codebrocamp-gmailcoms-projects.vercel.app"
export const IMG_URL = "https://server-3seejeyjs-codebrocamp-gmailcoms-projects.vercel.app/images/"
